language: node_js

node_js:
  - "8"

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/

cache:
  yarn: true
  directories:
    - ./node_modules/

before_install:
  - export TRAVIS_SOURCE_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}

before_script:
  - if [ "$TRAVIS_SOURCE_BRANCH" = "master" ]; then
      curl --location https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter;
      chmod +x ./cc-test-reporter;
      ./cc-test-reporter before-build;
    fi

script:
  - yarn run lint
  - yarn run test

after_script:
  - if [ "$TRAVIS_SOURCE_BRANCH" = "master" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi

notifications:
  email:
    on_failure: change
