language: node_js

node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules

script:
  - node --version
  - yarn --version
  - yarn run lint && yarn run test

after_success:
  - yarn global add codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info

notifications:
  email:
    on_failure: change
